  language: node_js
  node_js:
    - 'stable'
  services:
    - mongodb
  env:
    - MONGODB_URI=mongodb://localhost/test
  before_script: npm install
  script:
    - npm test
    - npm run lint
  branches:
  only:
  - master
